package com.gigledger.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a registered gig worker.
 *
 * - id: UUID primary key (auto-generated by Hibernate — no sequence needed)
 * - email: used for Phase 1 login; unique and non-null
 * - passwordHash: BCrypt-hashed password stored in DB; never returned in API responses
 * - phone_number: nullable for now; will be the primary identifier in Phase 2 (OTP auth)
 * - languagePref: future use for i18n (e.g., "hi", "ta", "en")
 * - createdAt: auto-set on insert by Hibernate
 */
@Entity
@Table(name = "users")  // "user" is a reserved word in PostgreSQL
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    @Id
    @UuidGenerator
    @Column(updatable = false, nullable = false)
    private UUID id;

    @Column(unique = true, nullable = false)
    private String email;

    @Column(nullable = false)
    private String passwordHash;

    @Column(nullable = false)
    private String name;

    // Nullable — to be used in Phase 2 for OTP-based login
    @Column(unique = true)
    private String phoneNumber;

    // "en", "hi", "ta", etc. — for future i18n support
    @Column(length = 10)
    @Builder.Default
    private String languagePref = "en";

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;
}
